### ISSUE TITLE
Diagnostic output from dataset reader

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#102]
With the K2 files we support a rather complex format. In particular for such files it is important for debugging purposes to extract diagnostic information from the reader.

For that reason a data set reader should implement a function that outputs diagnostic information about a file.

- [ ] The diagnostic information should be included in the "Info" button display (Issue #100 )
- [ ] For HDF5-based files this could contain a dump of the tree.
- [ ] For HDF5-based files information about shape, data type, chunking, compression of the currently selected HDF5 data set
- [ ] For K2 data it should contain info about the frame ID sequence #63 
- [ ] For K2 data the estimated total number of frames #63 
- [ ] For K2 data the "first block offsets" of every sector #63

**Comment by uellue** [comment]
Awesome! :-) Works great now.
