### ISSUE TITLE
Release 0.8

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#1093]
# Release checklist

## Issues to be considered for this release:

* #1070 - finishing touches on jupyter integration? release on pypi?
* #1098 #1040 
* #1100 #1053
* #1101 #1052
* #1104

### Memory issues

* #964 
* #894 
* <strike>#1042</strike> adjourned 

## Before (using a release candidate package)

* [x] Review open issues and pull requests
* [x] Run full CI pipeline, including slow tests, on [Azure DevOps](https://dev.azure.com/LiberTEM/LiberTEM/_build?definitionId=3) - see https://dev.azure.com/LiberTEM/LiberTEM/_build/results?buildId=1046&view=results
* [x] Handle deprecation, search the code base for `DeprecationWarning`
      that are supposed to be removed in that release.
* [x] GUI dependency update with `npm install`
* [x] Review https://github.com/LiberTEM/LiberTEM/security/dependabot and update dependencies
* [x] Full documentation review and update, including link check using
      ``sphinx-build -b linkcheck "docs/source" "docs/build/html"`` #1098 
* [ ] Run complete test suite, including slow tests that are deactivated by default
      and tests that require sample files.
* [x] Update the expected version in notes on changes, i.e. from `0.3.0.dev0`
      to `0.3.0` when releasing version 0.3.0.
* [x] Update and review change log in `docs/source/changelog.rst`, merging
      snippets in `docs/source/changelog/*/` as appropriate. #1098 
* [x] Update the JSON files in the ``packaging/`` folder with author and project information #1098 
* [ ] Edit `setup.cfg` to exclude flaky tests temporarily from release builds
* [x] Create a release candidate using `scripts/release`. See `scripts/release --help` for details.
* [x] `Confirm that wheel, tar.gz, and AppImage are built for the release candidate on
      GitHub <https://github.com/LiberTEM/LiberTEM/releases>`_
* [x] Confirm that a new version with the most recent release candidate is created in the
      `Zenodo.org sandbox <https://sandbox.zenodo.org/record/367108>`_ that is ready for submission.
* [x] Install release candidate packages in a clean environment
      (for example:
      `python -m pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple 'libertem==0.2.0rc11'`)
* [x] For the GUI-related items, open in an incognito window to start from a clean slate
* [x] Correct version info displayed in info dialogue?
* [x] Link check in version info dialogue
* [x] Make sure you have test files of all supported types available
    * [ ] Include floats, ints, big endian, little endian, complex raw data
* [x] Open each test file
    * [x] Are parameters recognized correctly, as far as implemented?
    * [x] Any bad default values?
    * [x] Does the file open correctly?
    * [x] Have a look at the dataset info dialogue. Reasonable values?
* [x] Perform all analyses on each test file.
    * [x] Does the result change when the input parameters are changed?
    * [x] All display channels present and looking reasonable?
    * [x] Reasonable performance?
    * [x] Use pick mode.
* [x] Re-open all the files
    * [x] Are the files listed in "recent files"?
    * [x] Are the parameters filled from the cache correctly?
* [ ] Try opening all file types with wrong parameters
    * [ ] Proper understandable error messages?
* [x] Pick one file and confirm keyboard and mouse interaction for all analyses
    * [ ] Correct bounds check for keyboard and mouse? #967 #436 
* [x] Check what happens when trying to open non-existent files or directories in the GUI.
    * [x] Proper understandable error message?
    * [x] Possible to continue working?
* [x] Shut down libertem-server while analysis is running #1122
    * [ ] Shut down within a few seconds?
    * [ ] All workers reaped?
* [ ] Check what happens when trying to open non-existent files by scripting.
    * [ ] Proper understandable error message? TODO automate?
* [ ] Check what happens when opening all file types with bad parameters by scripting
    * [ ] Proper understandable error message? TODO automate?
* [x] Run libertem-server on Windows, connect to a remote dask cluster running on Linux,
  open all file types and perform an analysis for each file type.
* [x] Use the GUI while a long-running analysis is running
    * [x] Still usable, decent response times? Subjectively improved by dynamic scheduling!
* [x] Confirm that pull requests and issues are handled as intended, i.e. milestoned and merged
  in appropriate branch.

## After releasing on GitHub

* [x] Confirm that all release packages are built and release notes are up-to-date
* [x] Install release package
* [x] Confirm correct version info
* [x] confirm package upload to PyPI
* [x] Publish new version on zenodo.org
* [x] Update documentation with new links, if necessary
    * [x] Add zenodo badge for the new release to Changelog page #1124 
* [x] Send announcement message on mailing list
* [x] Edit `setup.cfg` to include flaky tests again
* [x] Bump version in master branch to next .dev0 (`./scripts/release bump v0.X.0.dev0 --commit`)
* [x] Add to institutional publication databases
* [x] Add the current LiberTEM version to [CVL](https://github.com/Chasdfracterisation-Virtual-Laboratory/CharacterisationVL-Software>) - add both the singularity and the .desktop file! - see https://github.com/Characterisation-Virtual-Laboratory/CharacterisationVL-Software/pull/129

**Comment by uellue** [comment]
- [ ] If possible, clarify which format we support in #805 and #1077. Refs https://github.com/LiberTEM/LiberTEM/pull/1077#issuecomment-909383527
   - [ ] Amend changelog
   - [ ] Include in SEQ documentation

**Comment by uellue** [comment]
During release testing, I ran into the memory issues again and couldn't even complete half the GUI tests on a machine with 32 GB RAM. With that outcome I'd tend to classify these issues as a blocker for the release, since objectively LiberTEM is not able to complete the release checklist in its current state. I'm adding the corresponding Issues to the list above.

**Comment by uellue** [comment]
Since the Jupyter integration and CoM are nice features that people are waiting for and the memory issues are not new, we could also release 0.8 with a note on known bugs, and fast-track a 0.8.1 release that adresses the memory issues. What do you think?

**Comment by sk1p** [comment]
As discussed, I'll have an in-depth look at the memory problem, and if possible fix this for 0.8

**Comment by sk1p** [comment]
For post-release work, see also https://github.com/LiberTEM/LiberTEM-jupyter-proxy/issues/6
