### ISSUE TITLE
Allow to influence "damage" of results

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#1449]
Use case: visualization of partial results  with `kind='single'` and possibly custom shape, but the UDF knows what parts of it are valid. Examples are SSB/WDD or possibly iCoM.

**Comment by sk1p** [comment]
Right now, there's a single `damage` attribute on `UDFResults`, which is always nav-shaped and represents the indices of the navigation space that are already contained in the results. This can be used, for example by the plotting functionality, to limit `kind='nav'` plots to valid areas.

In addition, we need to make available a `valid_data_mask` for each result buffer. 

By default, the `valid_data_mask` should:

1) Equal the damage for `kind='nav'` buffers
2) Equal `1` for `kind='sig'` and `kind='single'` buffers

Then, `UDF.get_results` needs to be able to influence this to build buffers that have custom validity. I think it makes sense to allow overriding the defaults for all `kind`s. For example, with a `kind='nav'` buffer, there may be border effects in the calculation that make intermediate results invalid at the border, which we want to cut off until the full result is available. We need to figure out how the API for this should look like.

We need to be careful to also consider the `roi` - is the `valid_data_mask` in the flattened shape if a `roi` is applied? Is it in respect to `raw_data` or in respect to `data`? I think we need to make up some example uses to figure this out.

This per-result-buffer valid data mask then needs to be consumed by the visualization (for proper `vmin`/`vmax` determination), and possibly by other downstream users, like `LiberTEM-live-server`.

## TODO

- [ ] make the `damage` available to UDFs (see #1593)
- [ ] Figure out how to handle `roi`s
- [ ] API for customizing `valid_data_mask` from `get_results`
   - [ ] method/function name bikeshedding
   - [ ] which namespace does it live in? `UDF.<something>`? Is it common enough to warrant a place there? Or is this something people would be happy to import if they need it?

**Comment by sk1p** [comment]
> * [ ]  API for customizing `valid_data_mask` from `get_results`
>   
>   * [ ]  method/function name bikeshedding
>   * [ ]  which namespace does it live in? `UDF.<something>`? Is it common enough to warrant a place there? Or is this something people would be happy to import if they need it?

I've pushed an initial design to #1593 in form of a (failing) test case. As discussed with @uellue, this uses masked arrays for both influencing the result and for data consumers using the `masked_data` property. This is backwards-compatible, and `data` and `raw_data` should behave exactly as before.

If we do it like this, there's actually no API change needed on the UDF side, just the addition of `masked_data` on the `BufferWrapper`.

We might want to think if we want to depend 100% on masked arrays in the interface, or if we want to make a thin wrapper around it such that we can switch out the implementation. I'm tending towards just accepting our fate and exposing the masked arrays as our API.
