### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#581]
The plan is to release LiberTEM 0.4.0 this week.

## What issues still need to be resolved before we cut the first RC?

- [x] Release LiberTEM-blobfinder and let LiberTEM depend on it, part of #261, see also https://github.com/LiberTEM/LiberTEM-blobfinder/issues/7
- [x] Info on restructuring in changelog - #579 
- [x] Open a browser after starting the server - #580
- [ ] ~~I'd also like to work on a rewriting the cache stats stuff - depending on how far I get, it may still be part of this release~~

## QA Using a release candidate

- [x] Review open issues and pull requests
- [ ] Full documentation review and update, including link check using `sphinx-build -b linkcheck "docs/source" "docs/build/html"` -- partly done in #590, continue later (@uellue)
- [x] Update the expected version in notes on changes, i.e. from 0.4.0.dev0 to 0.4.0 when releasing version 0.4.0.
- [x] Update and review change log in docs/source/changelog.rst, merging snippets in docs/source/changelog/*/ as appropriate.
- [x] Update the JSON files in the packaging/ folder with author and project information
- [x] Create a release candidate using scripts/release. See `scripts/release --help` for details.
- [x] Confirm that wheel, tar.gz, and AppImage are built for the release candidate on GitHub
- [x] Confirm that a new version with the most recent release candidate is created in the Zenodo.org sandbox that is ready for submission.
- [x] Install release candidate packages in a clean environment (for example: `pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple 'libertem==0.4.0rc1'`)
- [x] For the GUI-related items, open in an incognito window to start from a clean slate
  - [x] Correct version info displayed in info dialogue?
  - [x] Link check in version info dialogue
  - [x] Include floats, ints, big endian, little endian, complex raw data
  - [x] Open each test file
    - [x] Are parameters recognized correctly, as far as implemented?
    - [x] Any bad default values?
    - [x] Does the file open correctly?
    - [x] Have a look at the dataset info dialogue. Reasonable values?
  - [x] Perform all analyses on each test file
    - [x] Does the result change when the input parameters are changed?
    - [x] All display channels present and looking reasonable?
    - [x] Reasonable performance?
    - [x] Use pick mode.
  - [x] Re-open all the files
    - [x] Are the files listed in “recent files”?
    - [x] Are the parameters filled from the cache correctly? see #599 for one bug found
  - [x] Try opening all file types with wrong parameters: Proper understandable error messages?
  - [x] Pick one file and confirm keyboard and mouse interaction for all analyses: Correct bounds check for keyboard and mouse?
  - [x] Check what happens when trying to open non-existent files or directories in the GUI.
    - [x] Proper understandable error message?
    - [x] Possible to continue working?
  - [x] Shut down libertem-server while analysis is running
    - [x] Shut down within a few seconds?
    - [x] All workers reaped?
- [x] Check what happens when trying to open non-existent files by scripting: Proper understandable error message?
- [x] Check what happens when opening all file types with bad parameters by scripting: Proper understandable error message?
- [ ] Run all examples
  - [x] center_of_mass
  - [ ] pcmclustering (don't have the data here...)
  - [x] peak_selector
  - [x] radialfourier
  - [x] simple libertem API
  - [x] basic.py
  - [ ] digital-micrograph-basic.py (@uellue postponed, first update GMS)
- [x] Run libertem-server on Windows, connect to a remote dask cluster running on Linux, open all file types and perform an analysis for each file type.
- [x] Use the GUI while a long-running analysis is running: Still usable, decent response times?
- [x] Confirm that pull requests and issues are handled as intended, i.e. milestoned and merged in appropriate branch.

## After releasing on GitHub

- [x] Confirm that all release packages are built and release notes are up-to-date
- [x] Install release package
- [x] Confirm correct version info
- [x] confirm package upload to PyPi
- [x] Publish new version on zenodo.org
- [ ] Update documentation with new links, if necessary
- [x] Add zenodo badge for the new release to Changelog page
- [x] Send announcement message on mailing list
- [x] Bump version to 0.5.0.dev0

## First changes unrelated to release

- [ ] Bump optional dependency in libertem-blobfinder to `libertem>=0.4.0,<1` - see https://github.com/LiberTEM/LiberTEM-blobfinder/pull/20

~~Btw: I think we can drop "Copy test files of all supported types to a fresh location or purge the parameter cache" from the checklist, if we are using an incognito window for testing.~~

**Comment by sk1p** [comment]
As the release was done some time ago, I'm going to close this. The only major outstanding item is the documentation review, which is independent of any releases IMHO.
