### ISSUE TITLE
Hackathon "postprocessing"

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#627]
- [ ] update documentation from hackmd document: #638 
- [x] update credits
- [x] add organization landing page #623 
- [x] improve consistency in merge function #631, #1003
- [ ] docs for `DataSet.diagnostics` #637 
- [x] improve usability of `Shape`/`Slice` #630

**Comment by sayandip18** [comment]
Isn't this issue same as #638 ?

**Comment by uellue** [comment]
> Isn't this issue same as #638 ?

#638 is a specification and spin-off from this issue since @sk1p and I realized that this would be a bigger item.

**Comment by sayandip18** [comment]
>     * [ ]  update credits
 
What does this mean?

**Comment by sk1p** [comment]
> What is meant by updating credits?

Sorry we didn't answer this before. This was done in https://github.com/LiberTEM/LiberTEM/pull/708 - basically it means updating our contributor and creator files and crediting people from the hackathon for their contribution.

**Comment by uellue** [comment]
Closing this overview issue since the remaining issues have their own entry and can be adressed separately.
