### ISSUE TITLE
Clean solution for interaction with other code that uses Dask

### ISSUE THREAD

**Issue by uellue** [LiberTEM/LiberTEM#922]
In #921 it became evident that multiple Dask clusters and clients are easily created, but can lead to significant side effects and are cumbersome to manage. The default use pattern relies on registering one global Dask client and then implicitly using that one for all operations. That means one can accidentally switch the cluster or client for a user by starting a new cluster or instantiating a client somewhere down the line. That leads to weird errors that are hard to debug.

For that reason we should think through the interaction between LiberTEM and other projects that use Dask, like Hyperspy.

- [x] Avoid registering a default Dask client from LiberTEM code as far as possible -- we use `set_as_default=False`, not sure if there is more to be done. #921 shows that some side effects will remain, though.
- [x] Support running LiberTEM on an existing Dask client or cluster. That should already work in principle, it just needs a good interface, documentation and tests, in particular for threaded Dask workers.
- [x] Allow to register LiberTEM's Dask client/cluster as global client in a controlled fashion to make it available to be used for other purposes than LiberTEM.
- [x] Allow LiberTEM and other Dask clusters and clients started by a user to co-exist peacefully.
- [x] Make sure that integrations and user workflows work in all these scenarios
  - [x] Open Datasets as Dask arrays
  - [x] In the future, open Dask arrays as Datasets #384 
  - [ ] Use LiberTEM for map() functionality on lazy signals in Hyperspy (future)
  - [ ] How would the interactions with the "advanced executor" project #473 look like?

**Comment by uellue** [comment]
As a quick feedback, implementing `map()` for Hyperspy using LiberTEM would be a significant improvement for lazy signals.

Test: Summing each frame in a 220 MB BLO file by mapping `np.sum()` on my laptop.

* LiberTEM using a default Dask.Distributed client (not local cluster, plain vanilla with Dask.Distributed defaults): 1.47 s
* Hyperspy using a regular Signal: 2.19 s (second run without creating a Distributed client: 1.73 s)
* Hyperspy using a lazy signal on Dask.Distributed: 3 min 30 s
* Hyperspy using a lazy signal on regular Dask: ca. 41-46 s

As a side note, the much slower processing on a Dask.Distributed client might point in the direction that lazy loading may have some kind of issue with accidentally sending large amounts of data across the cluster instead of loading and reducing data locally, similar to what we experienced in the past. LiberTEM file readers might help with constructing good Dask arrays on a Dask.Distributed cluster.

**Comment by uellue** [comment]
Regarding supporting `map()` in Hyperspy: Currently, Hyperspy `map()` modifies an array in-place by default. Provided that the array is a plain NumPy array, this is efficient and might be used by Hyperspy users for things like gain correction where the result is as large as the input data. The result is then used for further calculations.

Using LiberTEM and Dask arrays, this would currently be problematic for two reasons:

1. The result array is as large as the input data, and LiberTEM would currently send that to the leader node rather than keeping it in the cluster since LiberTEM is designed for live *reduction* operations.
2. Dask arrays currently [don't support assignment into them](https://github.com/dask/dask/issues/2000), while LiberTEM relies heavily on assignment into arrays in its merge operations for efficiency and potentially many small update steps of the result. That means LiberTEM currently can't use Dask arrays for result buffers directly, but only buffers that support assignment, such as NumPy and CuPy arrays.

It would be good if running a LiberTEM UDF on a Dask array would not automatically generate a result on the leader node, but could also be used to construct the result as a Dask array that can stay in the cluster and be used for subsequent "lazy" computations. For `map()` support on large data with equally large results this could be implemented quite efficiently since the "default merge" could be done by stacking the results, resulting in a Dask array.

For custom merge, it would probably not be possible to support very large results yet. However, one could implement a lazy computation using Dask by wrapping the merge function in a simple "merge runner" that receives the merge buffer and the partial result as arguments and returns the merged result. These wrapped merge operations could then be chained together using the `dask.delayed` API. This would potentially create many copies, but as long as the data is small, the main concern would be Dask overheads.

The purpose for supporting Dask array results for custom merge would not be so much performance, but better support for the programming model of Hyperspy lazy signals where a result is constructed by chaining Dask array and delayed operations together and in the end calling `compute()`. That way, the user retains control on where and how to call `compute()` and not be forced to compute whenever running a LiberTEM UDF. 

In terms of implementation, one would probably need these items:
* An extension of Dask-based executors that can return `dask.delayed` handles for the task results instead of task results as NumPy arrays. This already more or less exists as internal functionality and just has to be exposed properly.
* A custom `run_for_dataset()` implementation that replaces the default LiberTEM UDF `merge()` with Dask array `stack()` or `concatenate()` for the "happy case" of nav results with default merge. For custom merge functions, it wraps them into a chain of `dask.delayed()` operations for the merge steps.

**Comment by uellue** [comment]
Discussions with @sk1p:

Currently, all data necessary to run a task is embedded within the task. The task is executed by running its argument-less `__call__()` method. To support Dask arrays as input data and re-use parameters between partitions that are expensive to calculate or move around in the cluster, one should separate properties that are embedded within the task from data that is supplied to a task as an argument by the executor. Such an argument could then, for example, be scattered in the cluster before running the tasks when using a `DaskJobExecutor`.

Candidates to be supplied as arguments:
* UDF parameters and aux data
* Partition information or data. In the case of Dask arrays as input data, this could be used to feed the relevant Dask array block(s) as NumPy array to the Task. That would allow the Dask scheduler to naturally assign tasks to the right workers.
* In the future possibly references to shared memory?
* A twin of `get_task_data()` to specify internal data that the UDF would like to share between partitions if possible, as opposed to `get_task_data()` itself which manages scratch space that will be modified and should not be shared.

One should be careful with side effects since arguments may or may not be shared by reference between tasks. As an example, default `dask.delayed` seems to use threading where modifications of an argument within a delayed function modifies the value in the main thread:

```python
from dask import delayed
import numpy as np

a = np.array([0])

def inc(a):
    a += 1
    return a

d = delayed()(a)
for i in range(100):
    d = delayed(inc)(d)

d.compute()

a
# a is now array([100])
```

Modifying arguments is discouraged, so this example is actually an antipattern: https://docs.dask.org/en/latest/delayed-best-practices.html#don-t-mutate-inputs

However, the fact that the exact same memory is used for all the tasks with a threaded executor is great for cache efficiency and would help with SSB parallelization in https://github.com/Ptychography-4-0/ptychography

Care should be taken with `MaskContainer` since, on the one hand, it would be great if the tile cache can be shared between workers. On the other hand, requesting a tile changes the state of the `MaskContainer`. However, requesting an item from the `MaskContainer` is idempotent, and it SHOULD be ok since the `functools.lru_cache` that manages the state of `MaskContainer` seems to be thread-safe: https://github.com/python/cpython/blob/3.6/Lib/functools.py#L470

In that sense, being able to share the `MaskContainer` between partitions seems to be quite feasible. One could also consider to move from a purely process-based default Dask executor to a threaded one or mixture of threads and processes to make good use of this capability.

**Comment by uellue** [comment]
This might be a good time to address the AUX data handling as well: #626 Right now, they get a special treatment in `UDF.copy_for_partition()` and then `AuxBufferWrapper.new_for_partition()`. In the future, the whole aux data should probably be scattered in the cluster. Possibly the executor could take care of slicing this for the partitions?

This seems a bit similar to the executor taking over the merging of result buffers from the UDF for default merge of `kind='nav'` buffers in the delayed "happy path". Maybe one could delegate that to the executor by default, not only for delayed, actually?

**Comment by uellue** [comment]
> As a quick feedback, implementing `map()` for Hyperspy using LiberTEM would be a significant improvement for lazy signals.
> 
> Test: Summing each frame in a 220 MB BLO file by mapping `np.sum()` on my laptop.
> 
> * LiberTEM using a default Dask.Distributed client (not local cluster, plain vanilla with Dask.Distributed defaults): 1.47 s
> * Hyperspy using a regular Signal: 2.19 s (second run without creating a Distributed client: 1.73 s)
> * Hyperspy using a regular Signal, `parallel=False`: 450 ms
> * Hyperspy using a lazy signal on Dask.Distributed: 3 min 30 s
> * Hyperspy using a lazy signal on regular Dask: ca. 41-46 s
> 
> As a side note, the much slower processing on a Dask.Distributed client might point in the direction that lazy loading may have some kind of issue with accidentally sending large amounts of data across the cluster, similar to what we experienced in the past in LiberTEM at some occasions. LiberTEM file readers might help with constructing good Dask arrays on a Dask.Distributed cluster.

Recently `map()` has been significantly improved in Hyperspy: https://github.com/hyperspy/hyperspy/pull/2617

We should compare again as soon as we have Dask array input support. In particular Dask arrays that are chunked in the signal dimension could be interesting, since they have to be rechunked in the improved Hyperspy `map()` function.

**Comment by uellue** [comment]
Discussion with @matbryan52 and @sk1p :

* Move some of the buffer management to executor-specific code
* Move per-dataset processing from `UDFRunner` closer to executor-specific code
