### ISSUE TITLE
Release 0.6

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM#942]
# Release checklist

## Remaining issues

See [0.6 milestone](https://github.com/LiberTEM/LiberTEM/issues?q=is%3Aopen+milestone%3A0.6+sort%3Aupdated-desc)

## Before (using a release candidate package)

- [x] Review open issues and pull requests
- [x] Handle deprecation, search the code base for DeprecationWarning that are supposed to be removed in that release.
- [x] Full documentation review and update, including link check using sphinx-build -b linkcheck "docs/source" "docs/build/html"
- [x] Run complete test suite, including slow tests that are deactivated by default and tests that require sample files.
- [x] Update the expected version in notes on changes, i.e. from 0.3.0.dev0 to 0.3.0 when releasing version 0.3.0.
- [x] Update and review change log in docs/source/changelog.rst, merging snippets in docs/source/changelog/*/ as appropriate.
- [x] Update the JSON files in the packaging/ folder with author and project information (see also #827)
- [x] Edit setup.cfg to exclude flaky tests temporarily from release builds
- [x] Create a release candidate using scripts/release. See scripts/release --help for details.
- [x] Confirm that wheel, tar.gz, and AppImage are built for the release candidate on GitHub
- [x] Confirm that a new version with the most recent release candidate is created in the Zenodo.org sandbox that is ready for submission.
- [x] Install release candidate packages in a clean environment (for example: pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple 'libertem==0.6.0rc1')
- [x] For the GUI-related items, open in an incognito window to start from a clean slate
- [x] Correct version info displayed in info dialogue?
- [x] Link check in version info dialogue
- [ ] Make sure you have test files of all supported types available
  - [ ] Include floats, ints, big endian, little endian, complex raw data
- [x] Open each test file
  - [x] Are parameters recognized correctly, as far as implemented?
  - [x] Any bad default values?
  - [x] Does the file open correctly?
  - [x] Have a look at the dataset info dialogue. Reasonable values?
- [x] Perform all analyses on each test file.
  - [x] Does the result change when the input parameters are changed?
  - [x] All display channels present and looking reasonable?
  - [x] Reasonable performance?
  - [x] Use pick mode.
- [x] Re-open all the files
  - [x] Are the files listed in “recent files”?
  - [x] Are the parameters filled from the cache correctly?
- [x] Try opening all file types with wrong parameters
  - [x] Proper understandable error messages? #968
- [x] Pick one file and confirm keyboard and mouse interaction for all analyses
  - [x] Correct bounds check for keyboard and mouse? 
        * Disk, ring, FFT, Clust, round ROI: (Outer) radius can be increased to infinity -- not sure if bug or feature
        * Rect ROI, clustering: Both selectors unbounded #967
- [x] Check what happens when trying to open non-existent files or directories in the GUI.
  - [x] Proper understandable error message?
  - [x] Possible to continue working?
- [x] Shut down libertem-server while analysis is running 
  - [x]  Shut down within a few seconds? Mostly yes, with exceptions. #954 #964 
  - [x] All workers reaped? 
- [x] Check what happens when trying to open non-existent files by scripting.
  - [x] Proper understandable error message? TODO automate?
- [x] Check what happens when opening all file types with bad parameters by scripting
  - [x] Proper understandable error message? TODO automate?
- [x] Run all examples: see #973 
- [x] Run libertem-server on Windows, connect to a remote dask cluster running on Linux, open all file types and perform an analysis for each file type.
- [x] Use the GUI while a long-running analysis is running
  - [x] Still usable, decent response times? Mostly yes, with exceptions. #954

- [x] Confirm that pull requests and issues are handled as intended, i.e. milestoned and merged in appropriate branch.

## After releasing on GitHub
- [x] Confirm that all release packages are built and release notes are up-to-date
- [x] Install release package
- [x] Confirm correct version info
- [x] confirm package upload to PyPi
- [x] Publish new version on zenodo.org
- [x] Update documentation with new links, if necessary
  - [x] Add zenodo badge for the new release to Changelog page
- [x] Send announcement message on mailing list
- [x] Edit setup.cfg to include flaky tests again
- [x] Bump version in master branch to next .dev0
- [x] Add the current LiberTEM version to CVL (add both the singularity and the .desktop file!)

**Comment by sk1p** [comment]
Just as a note, 0.6.0rc0 did not finish, as there were two problems:

1) `nest-asyncio` did a release 1.5.0 just before us, which was broken. They quickly followed up with 1.5.1, which fixed the problem
2) The username passed on to `twine` was wrong, it needs to be `__token__`, not `libertem_bot`. This should now be fixed for `0.6.0rc1`

**Comment by sk1p** [comment]
Zenodo tokens are also still missing @uellue - can we fix that tomorrow morning? rc1 is available for testing, so we can continue anyways.

**Comment by uellue** [comment]
FYI, I started going through the reference data and made it until NeXus. More next week...

**Comment by sk1p** [comment]
We should probably also make sure that 0.6 works with the next numba release:

https://numba.discourse.group/t/numba-0-53-0-and-llvmlite-0-36-0-release-candidates/504

**Comment by sk1p** [comment]
> We should probably also make sure that 0.6 works with the next numba release:
> 
> https://numba.discourse.group/t/numba-0-53-0-and-llvmlite-0-36-0-release-candidates/504

Test suite passes, cursory usage tests looked fine :+1:

**Comment by sk1p** [comment]
CVL update submitted: https://github.com/Characterisation-Virtual-Laboratory/CharacterisationVL-Software/pull/115

**Comment by uellue** [comment]
@AnandBaburajan @twentyse7en your contributions are now finally released with version 0.6! Both reshaping and templates are great features that are among the highlights of this release. 🚀  Thanks again!

**Comment by uellue** [comment]
Post release checklist completed, closing! 🍾

**Comment by AnandBaburajan** [comment]
> @AnandBaburajan @twentyse7en your contributions are now finally released with version 0.6! Both reshaping and templates are great features that are among the highlights of this release.  Thanks again!

Thanks to you and @sk1p for the opportunity! I'll get back to my pending issues once I'm done with my exams and job-hunt! Looking forward to keep contributing to LiberTEM!
